### ISSUE TITLE
[Feature] Organisations Filter UI

### ISSUE THREAD

**Issue by vogelino** [SocialChangeLab/media-impact-monitor#122]
null

<sub>[VOG-284](https://linear.app/vogelino/issue/VOG-284/[feature]-organisations-filter-ui)</sub>

**Comment by davidpomerenke** [comment]
@vogelino let's discuss this before starting with the implementation.

Some questions that I still have:
- Do we actually need an organization filter, or is a topic filter enough (that is, all climate orgs / all animal orgs / etc.)
  - Maybe the user need behind this is to have a focus on one (or more) specific organizations. Maybe we can meet this better by improving the highlighting system of the protest plot, rather than by adding filters.
  - Separate pages for each organization might also be a better way.
